# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install: pip3 install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
  - export FLASK_DEBUG=1
  - export FLASK_CONFIG_FILE="$TRAVIS_BUILD_DIR/config.py"
env:
  - 
script: python3 flaskr_tests.py